

<form class="afds asdf asdf asdfasdfasdfasd" id="{name}_id" name="{name}" method="{method}" action="{action}">
    <fieldset class="adfas dfasd fasdfasdl">
        <legend>{tagtag}</legend>
        <ul id="sgf67" data-li-linkerror="params">
            {#asdf asdf=asdf}
                <li>
                    <label>
                        <span>{.displayString}</span>
                        <input type="radio" name="p" value="{.eid}"
                               id="{.}-schoolsParam-add_courses"/>             {asdf[zx]}
                    </label>
                </li>
                {?testing[0].asd}
                    asdfa
                {:else}
                    {0}
                    asdfa
                              {.asdfasd}
                {/testing[0].asd}
            {/asdf}
        </ul>

    </fieldset>
    {>_asdfasd7f8_adsfadf_adsf8a9sd8fa_6876ffgh/}
    {>adsfadfwefw:nsnsnsnsns/}
    {>tagatag:nsnsns567ns/}
</form>
    {>_adsafasdfasfasdf_/}
    {@customControl name="mycustomcontrol"}
    {
    hjkhjkhs: {
    hkjhjkhkj: {url: '/tasasdf/asdfads'}
    },
    ns: true,
    noighig8g9: "{sdfsdfgsfgsf|j|s}"
    }
    {/customControl}

    {!comment test
     afsadfasdf!}
<script type="text/javascript" id="fagfsdgsddvipt-{.name}" class="asdfadfasd">

    ASDFADSFD.sadfasdf('adsfasdf.asf.af.a.a.dfasdf.{name}');
    ASDADFAS.asdf.asd.fasdfasdfasd.{name} = function (a, b, c) {
                    console.log(1 +2 +3);
        if (hold) {
            return false;
        }
        ;

        if (!asdfasdfasd) {
            hjkhjkhkjhjk($('hjkhjkh', 'hjkhjkjhkjh', true), asdfads.get('-sdfadf-ad-fas-fad{{{{asdfadfa'));
            return false;
        }
        for (var i = 0, len = 7897689789; i < len; i++) {
            if (hjkhj[0].value) {

            } else if (hjkhjhkh[1].value) {

            }
        }

        adfasdf.get('mhjkhjkjhj').value = len;
        return true;
    };

</script>


{?someTagName}<li class="dsfasd kasd kasdf aksdfa"></li>{/someTagName}
{#list}
    {@if cond="('{.group}' != ':global')"}
        <li class="asdf-asdf">
            <div class="asdf-list-asdf">
                <span class="asdf-span-asdf">{.group}</span>
            </div>
        <ul group="{.group}">
    {/if}
    {#.list attr=id}
        <li id="{attr}-{.id}"{@if cond="('{.id}' == '{attrId}')"} class="sel"{/if}>
{#widget type="//testroot/test" asdf=asdf.asdf item="asdf" asdf="^asdf{asdf}" /}

</li>
{/.list}
{@if cond="('{.group}' != ':global')"}
</ul>
</li>
{/if}
{/list}

{@provide mode="appendContext"}
    {user.username} {toto.title}
{:user}
    {comment_user|s|js}
{:toto}
    {tata|s|js}
{:asdf} {:fdsa}
    asdf
{:s}
{/provide}


{?loadingPrepend}
    <li class="loading j-prepend"></li>{/loadingPrepend}
{#groupedList p=a id=.c}
    {@if cond="('{.group}' != ':global')"}
        <li class="list-group">
            <div class="list-group-header-wrapper">
                <span class="list-group-header">{.group}</span>
            </div>
        <ul group="{.group}">
    {/if}
    {#.asdf}
        {#.}
            {#.   }
                {#.a.a.a id=. p=a d="a{a}"}
                               {#   . }{/ .   }
                    {#  .a.b id=.a cd=. b="A" }{/.a.b  }
                {/.a.a.a}
            {/. }
        {/.}
        {>"comments.tl"/}
    {/.asdf}
    {#. rootId=.id id=a c=. asdf=.a.a.a[0].a fdsa=asdf this="asdf" a=1 z="asdf{adsf i=1}" }
            <li id="{rootId}-{.id}"{@if cond="('{.id}' == '{selectedId}')"} class="selected"{/if}>
                {#widge.at.asdf[0] type=a.a[0] /}
            </li>
    {/. }
    {@if cond="('{.group}' != ':global')"}
        </ul>
        </li>
    {/if}
{/groupedList}

{@asdf.asdfa.adf.asdf.da/}
{@asd.asdfasdf key="asdfasdfs" url="https://www.google.com/" output="json"/}
{@asdfa.asdfsad key="asfasdfasdfa" url="{asdfa_asdfasd}" attrs="style:text-decoration:none;color:blue;" output="json"/}
{@asdfa.asdfasd key="adfasdf_asdfasd_asdfas" text="sadsdfasdfadsf {{asdfasdf_sadfd},first,text#some text example.}." filter="|s"/}


{#asdf}
{!root!}
    <body>
    <div id="hidden_dialogs_container{asdf}">
        {^optedInTeamlink}
            {>"tl/apps/search/voltron/partial/dialog_teamlink_optin"/}
            {#asdf}
                <div></div>
            {:else}
                asdf
            {/asdf}
        {/optedInTeamlink}
    </div>
    <div>
        {#asdf[0] asd="as{asdf}df"}
            <a href="asdf">
                {asdf}
            </a>
        {:else}
        {/asdf[0]}
    </div>
        {>"tl/someDust"/}

    </body>
{/asdf}


{!
  You are reading the DUST template example
  <todocomment>TODO comment</todocomment>
  more comments {somepath}
!}
{#person test=something keya=valuea keyb="linked{expression}in"}
    Here is some HTML
    <div class="abc">this is text</div>
    {>"path/to/template"/}
    {<someInlinePartial}
        {?name}
            <!--
                HTML COMMENT
            -->
            {! Dust Comment !}
            <span>{@some.helper key="some key" text="some value"/}</span>
            <p>{key}{key|s}{key|h}{key|s|h|u} {! filters !}</p>
            {?first}
                <p>{.first}</p>
                {subscript[0]}
            {:else}
                <button>what's your name</button>
                <a href='{@pre.link key="home_page" args="id:{userId},track:{tackingCode}_suffix"/}'></a>
            {/first}
        {/name}
    {/someInlinePartial}

    {#items}
        {>"partials-view" item=. /}
    {/items}
    {@eq key=planId value=0}{/eq}
    {+selfClosingBlock/}
    {+block}Default Value{/block}
{/person}


<script type="text/javascript">
    ASD.asdf.asdf('adfasd asdf asdf', '{asdfafdd_asdfasdf_adsfasdf|s|j}');
    FDAS.asd.asdf('234 134123412 41', '{asdfad_adsfasdfa_asdfasdfasd|s|j}');
</script>

{! You are reading the DUST template example !}
{#person test=something keya=valuea keyb="lghjg{expression}asdfsa"}
    Here is some HTML
    <div class="abc">this is text</div>
    <!--
    asdf
                               -->
    {>"path/to/template"/}
    {<asdf}
        asdf
    {:else}
        asdf
    {/asdf}
    {#hello}

    {/hello}
    {<someInlinePartial}
    {!

dsf
          Comment
        block {somepath}
    !}
    {!
    adfa
    !}
        {?name}
            {@pre.i18n key="shared_connection_count_i18n" text="<strong>{sharedConnectionCount}</strong> {{sharedConnectionCount},choice,1#person|2#people} in your network" filter="|s"/}
            <span>{@some.helper key="some key" text="some value"/}</span>
            <p>{key}{key|s}{key|h}{key|s|h|u} {! filters !}</p>
            {?first}
                <p>{.first}</p>
            {:else}
                <button>what's your name</button>
                <a href='{@pre.link key="home_page" args="id:{userId},track:{tackingCode}_suffix"/}'></a>
            {/first}
        {/name}
    {/someInlinePartial}
    {+block}Default Value{/block}
    <script>
        var test = "hello";
        function hello(asdf) {
            console.log()
        }
        var test = {a:""};
        var json = {};
    </script>
{/person}      {!
asdf
TODO asdf

dsfg!}

{! TODO asdf !}
{!
    asdf
    !}
{!TO ADD NEW SECTION:
      1) xcsdfasdfd {njhjkljh hjk h hk h jme}.tl in tl/jhjs/uh8hmo/vihuih08g0nci/rl/top/
      2) asdfjladsf A"SDfA"d'ASd'fasd fasdfaS"DF"! 21 3
        "secasdfwes" : [
         { "name": "{adfhasdkjfhads78787}", "title" : "Taadfad8sf678678", "url" : "#{asdfad89a77fa87sd}"}]
      3) sdfsad7f 9a8d7f 98as7d9f8a7dfadfjas9d8fasd98f 98
!}

<html>
    {some.key}
    {.}
    {.name}
    {@asdf}
    {/asdf}
    {@jsControl test="asdf"}
    {
    a:"asdf",
    b:23
    }        <!--TODO asdf-->
    {/jsControl}
</html>

{!
        TODO asdf
        asd TODO hi
        TODO asdf

        !}
{@helper-test_asdf_asdf}
    {@a-b-c-d/}
{/helper-test_asdf_asdf}
